//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEPS_Entities : DbContext
    {
        public SEPS_Entities()
            : base("name=SEPS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_PERSONA> VW_PERSONA { get; set; }
        public virtual DbSet<SA_PROGRAMA> SA_PROGRAMA { get; set; }
        public virtual DbSet<SA_LKP_ALTA> SA_LKP_ALTA { get; set; }
        public virtual DbSet<VW_RAZON_ALTA> VW_RAZON_ALTA { get; set; }
    }
}
