//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EXTRACCIONES_SA_DIS
    {
        public string System_Transaction_Type { get; set; }
        public string State_Code { get; set; }
        public string Reporting_Date { get; set; }
        public string Provider_Identifier { get; set; }
        public string Client_Identifier { get; set; }
        public string Co_Dependant { get; set; }
        public string Type_of_Service { get; set; }
        public string Date_Last_Contact { get; set; }
        public string Date_of_Discharge { get; set; }
        public string Reason_for_Discharge { get; set; }
        public string Provider_ID_at_Admission { get; set; }
        public string Client_ID_at_Admission { get; set; }
        public string Co_dependent_Collateral { get; set; }
        public string Client_Transaction_Type_AD { get; set; }
        public string Date_of_Admision { get; set; }
        public string Type_of_Service_AD { get; set; }
        public string Date_of_Birth_at_AD { get; set; }
        public string Sex_at_AD { get; set; }
        public string Race_at_AD { get; set; }
        public string Ethnicity_at_AD { get; set; }
        public string Substance_Pro_Code_Primary { get; set; }
        public string Substance_Pro_Code_SECUNDARIA { get; set; }
        public string Substance_Pro_Code_Tertiary { get; set; }
        public string Frecuency_of_Use_Primary { get; set; }
        public string Frecuency_of_Use_SECUNDARIA { get; set; }
        public string Frecuency_of_Use_Tertiary { get; set; }
        public string Living_Arrangements { get; set; }
        public string Employment_Status { get; set; }
        public string Detailed_Not_In_Labor_Force { get; set; }
        public string Number_of_Arrests_in_30_Days_Prior_Dis { get; set; }
        public string Frecuency_of_Attendance { get; set; }
        public string Client_Transaction_Type { get; set; }
        public string Diagnostic_Code_Set_Identifier { get; set; }
        public string MH_Diag_Code_Primary_ICD_10 { get; set; }
        public string MH_Diag_Code_Secondary_ICD_10 { get; set; }
        public string MH_Diag_Code_Tertiary_ICD_10 { get; set; }
        public string Smi_Sed_Status { get; set; }
        public string School_Attendance_Status { get; set; }
        public string Education { get; set; }
        public string Escala_GAF { get; set; }
        public int Perfil { get; set; }
        public int Episode { get; set; }
        public System.DateTime FE_PERFIL { get; set; }
        public short PK_PROGRAMA { get; set; }
        public Nullable<int> FK_ESTATUS_PERFIL_TEDS { get; set; }
    }
}
